services:
  # 1. INGESTION SERVICE (Python App)
  ingestion:
    image: ghcr.io/cynicdog/uptown-downtown/ingestion:latest
    pull_policy: always
    container_name: mta_ingestion
    platform: linux/amd64
    volumes:
      - delta-volume:/app/data/delta
    environment:
      - DELTA_BASE_PATH=/app/data/delta
      - SPARK_DRIVER_HOST=ingestion
      - SPARK_LOCAL_IP=ingestion
    restart: on-failure
    networks:
      - mta-net

  # 2. QUERY SERVICE (Spark Thrift Server)
  query:
    image: apache/spark:3.5.1
    container_name: mta_querya
    platform: linux/amd64
    volumes:
      - delta-volume:/delta
    ports:
      - "10000:10000" # Thrift Server port
      - "10001:10001" # Hive Metastore port
    environment:
      - DELTA_BASE_PATH=/delta
      - SPARK_HOME=/opt/spark-3.5.1-bin-hadoop3
      - PATH=/opt/spark-3.5.1-bin-hadoop3/bin:$PATH
    entrypoint: >
      bash -c "
      exec /opt/spark-3.5.1-bin-hadoop3/sbin/start-thriftserver.sh \
      --master local[*] \
      --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension \
      --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog \
      --packages io.delta:delta-spark_2.12:3.2.0 \
      --foreground
      "
    depends_on:
      - ingestion
    networks:
      - mta-net

networks:
  mta-net:
    driver: bridge

volumes:
  delta-volume:
    driver: local
